export const cities = [
    'Rosario',
    'Santa Fe',
    'Campana',
    'Beijing',
    'Moscow',
    'Istanbul',
    'New York',
    'Tokyo',
    'London',
    'Paris',
    'Chicago',
    'San Francisco',
    'Sydney',
    'Madrid',
    'Rome',
    'Berlin',
    'Bangkok',
    'New Delhi',
    'Los Angeles',
   'Buenos Aires',
    'Mexico City',
    'Cairo',
    'Toronto',
    'Rio de Janeiro',
    'Sao Paulo',
    'Mumbai',
    'Amsterdam',
    'Vienna',
    'Dublin',
    'Athens',
    'Seoul',
    'Hong Kong',
    'Singapore',
    'Melbourne',
    'Wellington',
    'Nairobi',
    'Cape Town',
    'Lagos',
    'Accra',
    'Johannesburg',
    'Abuja',
    'Casablanca',
    'Dakar',
    'Dhaka',
    'Kuala Lumpur',
    'Manila',
    'Hanoi',
    'Dubai',
    'Riyadh',
    'Tehran',
    'Baghdad',
    'Beirut',
    'Jerusalem',
    'Laayoune',
    'Lisbon',
    'Barcelona',
    'Brussels',
    'Stockholm',
    'Oslo',
    'Copenhagen',
    'Warsaw',
    'Budapest',
    'Bucharest',
    'Kyiv',
    'Prague',
    'Zurich',
    'Geneva',
    'Vancouver',
    'Montreal',
    'Sydney',
    'Auckland',
    'Managua',
    'San Juan',
    'San Jose',
    'Lima',
    'Bogota',
    'Caracas',
    'Quito',
    'Asuncion',
    'La Paz',
    'Montevideo',
    'Brasilia',
    'Santiago',
    'Guayaquil',
    'Barranquilla',
    'Maracaibo',
    'Valencia',
    'Guatemala City',
    'Bridgetown',
    'Kingston',
    "St. George's",
    'Basseterre',
    "St. John's",
    'Tegucigalpa',
    'Panama City',
    'Port of Spain',
    'Roseau',
    'Castries',
    'Nassau',
    'Port-au-Prince',
    'Havana',
    'Belize City',
    'Belmopan',
    'Santo Domingo',
    'Panama City',
    'San Salvador',
    'Guatemala City',
    'Mexico City',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Ciudad Juarez',
    'Tijuana',
    'Leon',
    'Zapopan',
    'Naucalpan',
    'Nezahualcoyotl',
    'Merida',
    'San Luis Potosi'
  ]